/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.cron.jsonc --include-runtime=false --env-interface=CronEnv cron-worker-configuration.d.ts` (hash: b3fd887041d7e08304dbabc7a68e3a3c)
interface __BaseEnv_CronEnv {
	DB: D1Database;
	EMAIL: SendEmail;
	MONDAY_API_TOKEN: SecretsStoreSecret;
	COLAB_WEBHOOK: SecretsStoreSecret;
	ENVIRONMENT: "production";
	DASHBOARD_URL: "https://dashboard-v2.randall-d53.workers.dev";
	LOGIN_FROM_EMAIL: "dashboard@nhciviccommons.com";
	LOGIN_FROM_NAME: "Queerlective CoLab";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cron-worker");
	}
	interface Env extends __BaseEnv_CronEnv {}
}
interface CronEnv extends __BaseEnv_CronEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DASHBOARD_URL" | "LOGIN_FROM_EMAIL" | "LOGIN_FROM_NAME">> {}
}
