/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b33367c3f85d85553847add32d0230ba)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	MONDAY_API_TOKEN: SecretsStoreSecret;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	LOGIN_FROM_EMAIL: "login@queerlective.com";
	LOGIN_FROM_NAME: "Queerlective CoLab";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "LOGIN_FROM_EMAIL" | "LOGIN_FROM_NAME">> {}
}
