/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4f950047ecf9e05a5ddc60e603148911)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	MONDAY_API_TOKEN: SecretsStoreSecret;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	LOGIN_FROM_EMAIL: "dashboard@nhciviccommons.com";
	LOGIN_FROM_NAME: "Queerlective CoLab";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "LOGIN_FROM_EMAIL" | "LOGIN_FROM_NAME">> {}
}
